version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - psdata:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: ritehist/foodgram-back:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: ritehist/foodgram-front:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - backend
      - frontend
volumes:
  static_value:
  media_value:
  psdata: